title: "Hajime Ueda"
description: "Ph.D. candidate at the University of Tokyo"
theme: jekyll-theme-leap-day
show_downloads: false

email: hajimeueda@gmail.com
github_username: sacbow

include:
  - assets/css/custom.css
  - _includes/head-custom.html
  - _includes/nav.html

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

url: "https://sacbow.github.io"
baseurl: ""

plugins:
  - jekyll-include-cache
